name: Build and Push Docker Image

on:
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Build the Docker image
      run: | 
       COMMIT_ID=$(git rev-parse --short HEAD) && echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
       docker build . --file Dockerfile --tag techmodevops/test-repo:video-console-${COMMIT_ID}
       
    - name: Verify the Docker image
      run: docker images
          
    - name: Set CI to true
      run: | 
       echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
       echo "CI=${{ github.event.inputs.CI }}" >> $GITHUB_ENV
      if: github.event.inputs.CI

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Docker image to Docker Hub
      run: docker push techmodevops/test-repo:video-console-${COMMIT_ID}
