name: Build and Push Docker Image

on:
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Build the Docker image
      run: | 
       COMMIT_ID=$(git rev-parse --short HEAD) && echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
       docker build . --file Dockerfile --tag techmodevops/test-repo:video-console-${COMMIT_ID}
       
    - name: Verify the Docker image
      run: docker images
          
    - name: Set CI to true
      run: | 
       echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
       echo "CI=${{ github.event.inputs.CI }}" >> $GITHUB_ENV
      if: github.event.inputs.CI

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Docker image to Docker Hub
      run: docker push techmodevops/test-repo:video-console-${COMMIT_ID}

    - name: Set up kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl"  # Replace with the desired version
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client
    
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo "${{ secrets.DEV_KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    
    - name: Deploy to dev Environment
      run: |
          sed -i "s|\${COMMIT_ID}|$COMMIT_ID|g" k8s/dev_deployment.yml
          kubectl --insecure-skip-tls-verify apply -f k8s/dev_deployment.yml
              
    - name: Wait for 3 minutes
      run: sleep 60

    - name: Get Pod Name, Pod Status
      run: |
          POD_NAME=$(kubectl --insecure-skip-tls-verify get pods -n saas-dev --selector=app=hmsconsole -o custom-columns=":metadata.name" | head -n 2)
          POD_STATUS=$(kubectl --insecure-skip-tls-verify get pod $POD_NAME -n saas-dev -o jsonpath='{.status.phase}')
          echo "Pod Name: $POD_NAME", "Pod Status: $POD_STATUS"

    - name: Verify application URL
      run: |
        echo "Verifying application URL: https://devvideomeeting.charznow.com/"
        HTTP_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://devvideomeeting.charznow.com/)
        if [[ "$HTTP_RESPONSE" -ne 200 ]]; then
          echo "Application not accessible. HTTP response code: $HTTP_RESPONSE"
          kubectl --insecure-skip-tls-verify logs --tail=150 $POD_NAME -n saas-dev
          exit 1
        else
          echo "Application is up and running with HTTP response code: $HTTP_RESPONSE"
        fi

    - name: Rollback if URL check failed
      if: failure()  # This will trigger if the previous URL check fails (exit 1)
      run: |
        echo "Rolling back deployment due to application URL failure."
        kubectl --insecure-skip-tls-verify rollout undo deployment hmsconsole -n saas-dev

    - name: Get the image ID from the pod description
      run: |
          IMAGE_ID=$(kubectl --insecure-skip-tls-verify describe pod $POD_NAME -n saas-dev | grep "techmodevops/test-repo:video-console" | awk '{print $2}')
          # Display the image ID
          echo "Container Image ID: $IMAGE_ID"
